Introduce a test to measure CQL default read timeout on JanusGraph 0.6.x
This test fails with the following exception after ~5s:

com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S

Signed-off-by: Clement de Groc <clement.degroc@datadoghq.com>