Make StoreManager creation fail by changing order of dependencies
Our goal is to simulate a bug due to having metrics-core 3.x
appearing earlier than metrics-core 4.x in Java classpath during
unit tests.

`mvn dependency:tree` tells us that, by default, and due to how
janusgraph-cql's pom.xml is written, metrics-core 4.x will appear
before metrics-core 3.x by default.

As a consequence, the provided unit test succeeds when the pom.xml
is left untouched.

To observe the bug, we need to reverse the order of metrics-core
4.x and 3.x in the classpath. Moving janusgraph-backend-testutils
(which pulls gremlin-server and metrics-core 3.x) to the top of
dependencies will do that.

After moving janusgraph-backend-testutils, the unit test will fail
with exception NoSuchMethodError.